import type { EvaluationScenarioDefinition } from "./contracts";

const organizer = (path: string) => `/organizer/events/:eventSlug/${path}`;

export const evaluationScenarios: EvaluationScenarioDefinition[] = [
  scenario("CFP-S1", "Call for Papers", "Build and publish the CFP", "Organizer", organizer("cfp"), [organizer("settings"), organizer("cfp"), "/cfp/:eventSlug"], ids("CFP", 1, 4), "Draft CFP Form → immutable published form version with an enforced submission window.", "The public CFP reads the published form, event branding, tracks, and formats."),
  scenario("CFP-S2", "Call for Papers", "Draft, submit, and edit proposals", "Speaker", "/speaker/events/:eventSlug/submissions", ["/cfp/:eventSlug", "/speaker/events/:eventSlug/submissions", organizer("submissions")], ["CFP-05", "CFP-06", "CFP-07", "CFP-08", "CFP-09", "CFP-16"], "Speaker draft → submitted/versioned Submission; editing eligibility follows the CFP window.", "Organizer inbox receives canonical answers and Communications receives the confirmation outbox event."),
  scenario("CFP-S3", "Call for Papers", "Assign a reviewer and score", "Organizer → reviewer", organizer("evaluations"), [organizer("evaluations"), "/reviewer/events/:eventSlug/reviews"], ["CFP-10", "CFP-11"], "Review Assignment → reviewer-owned response and submitted completion state.", "Organizer evaluation progress and results read the same persisted response."),
  scenario("CFP-S4", "Call for Papers", "Decide, notify, hand off, and close CFP", "Organizer", organizer("submissions"), [organizer("submissions"), organizer("communications"), organizer("agenda")], ids("CFP", 12, 15), "Authoritative Decision → distinct linked Session/Event Speaker records; notification outcome is retained.", "Accepted program data moves to speaker operations, scheduling, communications, and integrations without re-entry."),
  scenario("ABS-S1", "Abstract Management", "Seed submissions with a co-author", "Speaker", "/speaker/events/:eventSlug/submissions", ["/cfp/:eventSlug", "/speaker/events/:eventSlug/submissions", organizer("evaluations")], ["ABS-11"], "Submission Participant with a role label is persisted beside the Submission.", "Organizer review and result views retain the participant credit."),
  scenario("ABS-S2", "Abstract Management", "Configure rounds, pools, assignments, and reminders", "Organizer", organizer("evaluations"), [organizer("evaluations"), organizer("communications")], ["ABS-01", "ABS-02", "ABS-03", "ABS-04", "ABS-05", "ABS-06", "ABS-08", "ABS-09"], "Review Plan/Rounds/scorecards/pools → scoped assignments and reminder deliveries.", "Reviewer queues, progress projections, and Communications consume the configured plan."),
  scenario("ABS-S3", "Abstract Management", "Score blind and verify aggregates/export", "Reviewer → organizer", "/reviewer/events/:eventSlug/reviews", ["/reviewer/events/:eventSlug/reviews", organizer("evaluations")], ["ABS-07", "ABS-10", "ABS-12", "ABS-13", "ABS-14"], "Blind assignment → isolated review/recusal, weighted aggregate, export, and advisory AI/human override records.", "Decision tooling consumes aggregates while peer and participant identity boundaries remain enforced."),
  scenario("SPK-S1", "Speaker Management", "Build roster and assign onboarding tasks", "Organizer", organizer("speakers"), [organizer("speakers"), organizer("tasks"), organizer("communications")], ids("SPK", 1, 6), "Person/Event Speaker → workflow status plus assigned dated Tasks and invitation delivery.", "Speaker portal, dashboard readiness, and Communications receive canonical assignments."),
  scenario("SPK-S2", "Speaker Management", "Complete onboarding in the portal", "Speaker", "/speaker/events/:eventSlug", ["/speaker/events/:eventSlug", "/speaker/events/:eventSlug/files"], ids("SPK", 7, 11), "Scoped Speaker Profile/task/file updates persist against only the active Event Speaker.", "Organizer roster, sessions, tasks, files, and public profile projections receive the updates."),
  scenario("SPK-S3", "Speaker Management", "Track progress and send bulk communications", "Organizer", organizer("speakers"), [organizer("speakers"), organizer("communications")], ids("SPK", 12, 16), "Task completion/logistics fields → progress projections and recipient-level communication outcomes.", "Dashboard readiness and delivery evidence consume real portal and provider state."),
  scenario("CNT-S1", "Content Management", "Set up content collection", "Organizer", organizer("tasks"), [organizer("tasks"), organizer("files")], ["CNT-01", "CNT-06"], "File-request Task → scoped Task Assignments and Deliverables with due dates and upload rules.", "Speaker file workspace receives only authorized requests."),
  scenario("CNT-S2", "Content Management", "Upload and version a deliverable", "Speaker", "/speaker/events/:eventSlug/files", ["/speaker/events/:eventSlug/files", organizer("files")], ids("CNT", 2, 5), "Authorized upload → immutable verified File Object and incrementing Deliverable Version with comments.", "Organizer files and deliverable workflow read the same private version history."),
  scenario("CNT-S3", "Content Management", "Track, review, approve, and export", "Organizer", organizer("files"), [organizer("files"), organizer("speakers"), organizer("publish")], ids("CNT", 7, 14), "Content/deliverable edits → attributed history, restore/approval, and persisted ZIP manifest.", "Publication eligibility, reminders, central library, and integrations consume approved canonical content."),
  scenario("AIA-S1", "AI Agenda", "Configure, place, trigger, and resolve conflicts", "Organizer", organizer("agenda"), [organizer("settings"), organizer("agenda")], ids("AIA", 1, 6), "Unscheduled Session → Placement in a Schedule Revision; conflicts are computed and clear after a valid move.", "Publishing and calendar generation consume the selected conflict-free revision."),
  scenario("AIA-S2", "AI Agenda", "Auto-schedule assist and publish", "Organizer", organizer("agenda"), [organizer("agenda"), organizer("publish"), "/events/:eventSlug/agenda"], ["AIA-07", "AIA-08"], "Deterministic auto-place → eligible revision → authoritative Publication live transition.", "All public program surfaces read the live revision without copied CMS records."),
  scenario("EMB-S1", "Public Widgets", "Tour four public browse widgets", "Anonymous attendee", "/events/:eventSlug/sessions", publicRoutes(), ["EMB-01", "EMB-02", "EMB-03", "EMB-04", "EMB-05", "EMB-06", "EMB-07", "EMB-08", "EMB-09", "EMB-12", "EMB-13", "EMB-14"], "No private mutation; public reads project approved, scheduled records from the live Publication.", "Sessions, speakers, agenda, itinerary, and gallery stay consistent through one Published Program query."),
  scenario("EMB-S2", "Public Widgets", "Build a persistent personal itinerary", "Anonymous attendee", "/events/:eventSlug/itinerary", ["/events/:eventSlug/itinerary", "/api/v1/public/program/:eventSlug/anonymous-itinerary/calendar.ics"], ["EMB-10", "EMB-11"], "Anonymous itinerary token → persisted selected Session links and deterministic iCalendar export.", "Reload and calendar consumers receive exactly the attendee's selected live sessions."),
  scenario("EMB-S3", "Public Widgets", "Generate embeds and verify consistency", "Organizer", organizer("publish"), [organizer("publish"), ...publicRoutes()], ["EMB-15", "EMB-16"], "Widget configuration versions persist without copying program records.", "External styled/basic/JSON/XML/iCal outputs read the same live canonical program."),
  scenario("CRM-S1", "Speaker CRM", "Build and organize the cross-event speaker database", "Organizer", "/organizer/organizations/:organizationId/speaker-crm", ["/organizer/organizations/:organizationId/speaker-crm"], ids("CRM", 1, 6), "Canonical Person → CRM metadata, notes, tags, imports, and deliberate duplicate merge.", "Event history and Speaker Profiles remain linked to one person."),
  scenario("CRM-S2", "Speaker CRM", "Source through pipeline and reuse across events", "Organizer", "/organizer/organizations/:organizationId/speaker-crm", ["/organizer/organizations/:organizationId/speaker-crm", organizer("speakers"), organizer("communications")], ids("CRM", 7, 12), "CRM enrollment/transition/segment → idempotent Event Speaker handoff and outreach recipients.", "Speaker Operations, Communications, and analytics consume the same canonical person."),
];

export const requiredRubricIds = evaluationScenarios
  .flatMap((item) => item.requirementIds)
  .filter((id) => !id.startsWith("CRM-"));
export const extraCreditRubricIds = evaluationScenarios
  .flatMap((item) => item.requirementIds)
  .filter((id) => id.startsWith("CRM-"));

function scenario(id: string, area: string, title: string, persona: string, entryRoute: string, routes: string[], requirementIds: string[], persistedTransition: string, downstreamHandoff: string): EvaluationScenarioDefinition {
  return { id, area, title, persona, entryRoute, routes, requirementIds, persistedTransition, downstreamHandoff };
}

function ids(prefix: string, start: number, end: number): string[] {
  return Array.from({ length: end - start + 1 }, (_, index) => `${prefix}-${String(start + index).padStart(2, "0")}`);
}

function publicRoutes() {
  return ["/events/:eventSlug/sessions", "/events/:eventSlug/speakers", "/events/:eventSlug/agenda", "/events/:eventSlug/itinerary", "/events/:eventSlug/gallery"];
}
